# Default values for aachart. sharedconfman
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Activa la instalacion del chart. Util para instalaciones globales
# Este chart debe desplegarse solo si se utiliza memoria compartida a nivel de worker. 
enabled: true

# Si se define como global (chart umbrella) estos valores serán sobreescritos con el valor global. 
image:
  # -- Repositorio de donde bajar los contenedores. Debe incluir el path completo incluyendo la / final.
  repository: zape-k8s-dockreg:5000/
  # Politica de pull
  pullPolicy: IfNotPresent

env:
  # -- Nivel de trazas del proceso: 0-Todas. 1-Solo de error e informativas
  NIVEL_TRAZAS:
    value:  "0"
  # -- Tipo de exporter de OpenTelemetry.  0-Ninguno, 1-Logs, 2-JaegerUDP, 3-JaegerHTTP
  CNF_OPENTELEMETRY_EXPORTER_TIPO:
    value: "0"
  # -- Host donde se envian los intervalos de OpenTelemetry (en conjuncion con CNF_OPENTELEMETRY_EXPORTER_PORT)
  # Si es por UDP, se suele enviar a localhots o a un DaemonSet (indicando en CNF_OPENTELEMETRY_EXPORTER_HOST status.hostIP)
  # Si es por HTTP se pone la direccion del jaeger agent, por ejemplo jaeger-agent.jaeger
  CNF_OPENTELEMETRY_EXPORTER_HOST:
    value: "jaeger-agent.jaeger"
  # -- Puerto donde se envian los intervalos de OpenTelemetry (en conjuncion con CNF_OPENTELEMETRY_EXPORTER_HOST)
  CNF_OPENTELEMETRY_EXPORTER_PORT:
    value: "6831"
  # -- Uso de cifrado en las conexiones 0MQ (las claves deben proporcionarse en el zmq-secret). Los procesos
  #    de FED y BELS tienen que tener la misma configuració
  CNF_ZMQ_CIFRADO:
    value: "1"
  # -- Variable para definir si la comunicacion con la BD se hace encriptada o no.
  # Valor 0 indica no encriptada, valor 1 encriptada.
  DATABASE_ENCRYPT:
    value: "1"
  # -- Tratamiento ante SIGTERM. 0-para, 2-indisponible y continua procesando lo que haya pendiente
  CNF_TRATAMIENTO_SIGTERM_CLOUD:
    value: "2"
  # -- Servicio AA para el que se despliega este chart (Etiqueta e Identificador)
  SERVICIO:
    value: "PREPAGO"
  SERVICIO_ID:
    value: "1"
  # -- Celula en la que se despliega el chart. Por defecto celula 1.
  CELULA:
    value: "1"
  # -- Variable para forzar que los procesos se comuniquen solo con funcionalides de la misma celula. Por defecto 0 para evitarlo.
  CNF_ZMQ_SOLO_MISMA_CELULA:
    value: "0"
  # -- Numero de instancias de un servidor que debe haber en tu mismo nodo para activar el envio solo a instancias de 
  #    tu mismo nodo worker (0 para desactivar la funcionalidad)
  CNF_ZMQ_UMBRAL_ENVIO_MISMO_NODO:
    value: "0"
  # -- Variable para definir el número de segundos que se mantienevivo  el pod una vez que se ha muerto el proceso. Util para depuracion
  SLEEP_AL_TERMINAR:
    value: "0"

sharedconfman:
  # -- Funcionalidad para el gestor de memoria compartida (nombre)
  funcionalidad: "SHAREDCONFMAN"
  # -- Funcionalidad para el gestor de memoria compartida (id)
  funcionalidadId: "150"

  startupProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    failureThreshold: 20

  image:
    # -- Repositorio de donde bajar el contenedor del sharedconman. Si se define sobreescribe al valor comun. Debe incluir el path completo incluyendo la / final.
    repository: #zape-k8s-dockreg:5000/
    # -- Nomre de la imagen del sharedconfman 
    imageName: sharedconfman
    # @ignored al generar doc automatica
    pullPolicy: IfNotPresent
    # @ignored al generar doc automatica
    #    tag: "x.y.z-n"
  resources:

exporter:
  image:
    # -- Repositorio de donde bajar el contenedor del exportador de metricas, para llevar los contadores de sharedconfman a prometheus. Si se define sobreescribe al valor comun. Debe incluir el path completo incluyendo la / final.
    repository: #zape-k8s-dockreg:5000/
    # -- Nomre de la imagen del exporter 
    imageName: metrics_aa_exporter
    # @ignored al generar doc automatica
    pullPolicy: #IfNotPresent
    # @ignored al generar doc automatica
    tag: "1.0.1"

  resources:
    limits:
      cpu: "50m"
      memory: "10Mi"

podAnnotations:
  # -- Anotacion para indicar a prometheus que debe recopilar metricas de estos pods
  prometheus.io/scrape: 'true'
  # -- Puerto donde se sirven las metricas
  prometheus.io/port: '9100'

# @ignored al generar doc automatica
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext:

# -- configuracion de seguridad del container, para activar sólo las capabilities necesarias. En un entorno de producción
#    lo recomendable es dejar todas desactivadas, ya que sólo se usan para depuración y no son necesarias para el servicio
securityContext:
  # @ignored al generar doc automatica
  runAsNonRoot: true
  # @ignored al generar doc automatica
  allowPrivilegeEscalation: false
  # @ignored al generar doc automatica
  capabilities:
    drop:
        - ALL
    add: []
    # systrace es para strace, pstack y gdb
    # netadmin y netraw son para ping.
    # el resto para tcpdump
    #add: ["SYS_PTRACE","NET_ADMIN","NET_RAW","SETUID", "SETGID","CHOWN","DAC_OVERRIDE","FOWNER","FSETID","KILL","SETUID","SETPCAP","NET_BIND_SERVICE","SYS_CHROOT","MKNOD","AUDIT_WRITE","SETFCAP"]

# @ignored al generar doc automatica
podSecurityContext:
