# Default values for aachart. simgencdr
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Activa la instalacion del chart. Util para instalaciones globales
enabled: true

replicas: 1
image:
  repository: zape-k8s-dockreg:5000/
env:
  # -- Nivel de trazas del proceso: 0-Todas. 1-Solo de error e informativas
  NIVEL_TRAZAS:
    value:  "0"
  # -- Tipo de exporter de OpenTelemetry.  0-Ninguno, 1-Logs, 2-JaegerUDP, 3-JaegerHTTP
  CNF_OPENTELEMETRY_EXPORTER_TIPO:
    value: "0"
  # -- Host donde se envian los intervalos de OpenTelemetry (en conjuncion con CNF_OPENTELEMETRY_EXPORTER_PORT)
  # Si es por UDP, se suele enviar a localhots o a un DaemonSet (indicando en CNF_OPENTELEMETRY_EXPORTER_HOST status.hostIP)
  # Si es por HTTP se pone la direccion del jaeger agent, por ejemplo jaeger-agent.jaeger
  CNF_OPENTELEMETRY_EXPORTER_HOST:
    value: "jaeger-agent.jaeger"
#    valueFrom:
#     fieldRef:
#        fieldPath: status.hostIP
  # -- Puerto donde se envian los intervalos de OpenTelemetry (en conjuntcion con CNF_OPENTELEMETRY_EXPORTER_HOST)
  CNF_OPENTELEMETRY_EXPORTER_PORT:
    value: "6831"
  # -- Uso de cifrado en las conexiones 0MQ (las claves deben proporcionarse en el zmq-secret). Los procesos
  #    de FED y BELS tienen que tener la misma configuració
  CNF_ZMQ_CIFRADO:
    value: "1"
  # -- Numero de instancias de un servidor que debe haber en tu mismo nodo para activar el envio solo a instancias de 
  #    tu mismo nodo worker (0 para desactivar la funcionalidad)
  CNF_ZMQ_UMBRAL_ENVIO_MISMO_NODO:
    value: "0"
  # -- Variable para definir si la comunicacion con la BD se hace encriptada o no.
  # Valor 0 indica no encriptada, valor 1 encriptada.
  # @default -- ...
  DATABASE_ENCRYPT:
    value: "1"

containerSecurityContext:
  capabilities:
    drop:
      - all
    # systrace es para strace, pstack y gdb
    # netadmin y netraw son para ping
    add: ["SYS_PTRACE","NET_ADMIN","NET_RAW","SETUID", "SETGID","CHOWN","DAC_OVERRIDE","FOWNER","FSETID","KILL","SETUID","SETPCAP","NET_BIND_SERVICE","SYS_CHROOT","MKNOD","AUDIT_WRITE","SETFCA"]

podAnnotations:
  # -- Anotacion para indicar a prometheus que debe recopilar metricas de estos pods
  prometheus.io/scrape: 'true'
  # -- Puerto donde se sirven las metricas
  prometheus.io/port: '9100'

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
