{{- if .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: listPodsCM-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "aachart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: listPodsCM-role
  apiGroup: rbac.authorization.k8s.io

{{- end }}

