# Default values for chart. monitor
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Activa la instalacion del chart. Util para instalaciones globales
enabled: true

# Si se define como global (chart umbrella) estos valores serán sobreescritos con el valor global. 
image:
  # -- Repositorio de donde bajar los contenedores. Debe incluir el path completo incluyendo la / final.
  repository: zape-k8s-dockreg:5000/
  # Politica de pull
  pullPolicy: IfNotPresent

reloadMonitorImage:
  # -- Repositorio de donde bajar el monitor de relecturas. Si se define sobreescribe el valor comun. Debe incluir el path completo incluyendo la / final.
  repository: #zape-k8s-dockreg:5000/
  # -- Nomre de la imagen del monitor de relecturas 
  imageName: monitor_relecturas
  # @ignored al generar doc automatica
  pullPolicy: #IfNotPresent
  # @ignored al generar doc automatica
  tag: 1.0.1

  #podAnnotations:
  # -- Anotacion para indicar a prometheus que debe recopilar metricas de estos pods
  #prometheus.io/scrape: 'true'
  # -- Puerto donde se sirven las metricas
  #prometheus.io/port: '9100'

podSecurityContext:

# -- configuracion de seguridad del container, para activar sólo las capabilities necesarias. En un entorno de producción
#    lo recomendable es dejar todas desactivadas, ya que sólo se usan para depuración y no son necesarias para el servicio
securityContext:
  # @ignored al generar doc automatica
  runAsNonRoot: true
  # @ignored al generar doc automatica
  allowPrivilegeEscalation: false
  # @ignored al generar doc automatica
  capabilities:
    drop:
       - ALL
    add: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
#resources:
#  limits:
#    cpu: "1"
#  requests:
#    cpu: 200m
